# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :matchbox do |matchbox|

    matchbox.vm.box = "generic/fedora30"
    matchbox.vm.hostname = "matchbox"
    matchbox.vm.network "private_network", ip: "192.168.0.254", virtualbox__intnet: "pxe_network"

    matchbox.vm.provider :virtualbox do |vb|
      vb.memory = '1024'
      vb.cpus = '1'
    end

    matchbox.vm.provision "shell", path: "config/setup.sh"
  end
end

